server:
  port: 8083

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  h2:
    console:
      enabled: true
      path: /console
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  boot:
    admin:
      url: http://localhost:8082
  application:
    name: LearnSpringBoot

security:
  basic:
    enabled: false
  ignored:
    - console/**
    - health

management:
  security:
    enabled: false
